### ISSUE TITLE
设置为text_ik类型的无法对整数进行分词，会自动将整数过滤掉

### ISSUE THREAD

**Issue by lightCraft2020** [magese/ik-analyzer-solr#1]
设置为text_ik类型的无法对整数进行分词，会自动将整数过滤掉，这个怎么处理呢？之前的低版本是可以的
![image](https://user-images.githubusercontent.com/11204164/46663282-4715ca00-cbf0-11e8-9cde-d94c2cf1509a.png)
如上图所示，b把数字3去掉了

**Comment by magese** [comment]
这是因为之前上传jar包里带的停用词文件里包含了这个词语，我会在下一个版本的jar包解决这个问题。
现在你可以选择将停用词都删掉，或者是下载最新的代码手动打成jar包。
